---
title: "MechaCarChallenge"
author: "Justin Kiehl"
date: "1/9/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
mecha_car <- read.csv('Resources/MechaCar_mpg.csv',stringsAsFactors = F) #read in dataset
```

```{r}
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,data=mecha_car) #generate multiple linear regression model
```

```{r}
summary (lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD,data=mecha_car))
```

```{r}
suspension_coils <- read.csv('Resources/Suspension_Coil.csv',stringsAsFactors = F) #read in dataset
```

```{r}
total_summary <- suspension_coils %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI), .groups = 'keep')
```

```{r}
lot_summary <- suspension_coils %>% group_by(Manufacturing_Lot) %>% summarize(Mean=mean(PSI), Median=median(PSI), Variance=var(PSI), SD=sd(PSI), .groups = 'keep')
```

```{r}
t.test(suspension_coils$PSI, mu=1500)
```

```{r}
t.test(subset(suspension_coils, Manufacturing_Lot =="Lot1")$PSI, mu=1500)
```

```{r}
t.test(subset(suspension_coils, Manufacturing_Lot =="Lot2")$PSI, mu=1500)
```

```{r}
t.test(subset(suspension_coils, Manufacturing_Lot =="Lot3")$PSI, mu=1500)
```

```{r}

```

```{r}

```






